version: '3'

services:
  chmiel_db:
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ChmielDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ChmielDB"]
      interval: 30s
      timeout: 60s
      retries: 3
    networks:
      - my_network


  chmiel_back:
    build:
#    image: chmiel_back
      context: .
      dockerfile: Dockerfile_back
    ports:
      - "8084:8084"
    depends_on:
      chmiel_db:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://chmiel_db:5432/ChmielDB
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: test
    networks:
      - my_network


  chmiel_front:
#    image: chmiel_front
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "3000:80"
    depends_on:
      - chmiel_back
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
