services:
  backend:
    image: chmiel_back
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    image: chmiel_front
    ports:
      - "8083:8083"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
