#
# Build stage
#
FROM maven:3.8.3-openjdk-17 AS build
ENV HOME=/spring
RUN mkdir -p $HOME
WORKDIR $HOME

ADD ./chmiel .

VOLUME maven_cache:/root/.m2
RUN mvn -X verify --debug -DskipTests
RUN mvn -X package --debug -DskipTests

#
# Package stage
#

FROM eclipse-temurin:17-jre-jammy 
ARG JAR_FILE=/spring/target/chmiel-0.0.2-SNAPSHOT.jar
COPY --from=build $JAR_FILE /app/runner.jar
EXPOSE 8084
ENTRYPOINT java -jar -Dport=8084 /app/runner.jar --debug
